---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-pull
  namespace: supreal-api
spec:
  encryptedData:
    .dockerconfigjson: AgCaG6k0uNhftFdpOT9xONthEV1LJJnlURW0ImX5nRYMhs0ZKXnjwSB+QsalaxD0IgXGrgBcVrBgNaVdO2SWJbQoBTQOXPswFB+Bnt+hgP4m2rx6mpjKAsM22GB2gc78wLXxkf7zT5OQ7IY80yb5qNZwAonldNnMW4heSVFdATNnBXVuU7HdAFl7YaXaNgkDTRzvIaA49n//IujJI0thFTAIxymXizJ1lnaysgdXhg/ocZ9eYMUzG6VABedtrvJc8Hx+psJwgr5BlzR/j+UH3jFoir2bqom2GIbjGXqhosTSI7GEvxsgx/Zz8FEq43OX/D5hp0OJmUx5ZFZjP1AF578nSpcnVHv52qSyvBMNIioypByCpHj1xPSWvNgERd4iMmqvTWLtDNbJ5BREi5VLy+PoS8ysnigGCUPsHEeEGCN0KPICMhv6niDU2jDlvKy5etLs+xskKOgazf2e6yA+WOpNU3YbBCOFu2o3o2cmH8VX0lZ9rwx1d5ayfAij6M+0RfAfH0zpP2TR/PnpMki+FBHUdeHQpLy97pwrUyPmpg89y+bBGgMePgZX3p7y/4Z4nG1eFo+dY76J46VAUpfKbpO2zaX0LGbpGvWIsJNdkazqAFY9ncyJwSf5OmFSlYMsnUEVsha9wXjJgV3tk3K8UFpB8eNS3VZFTVb0tehOxiOHnngp6PuArTEKI81DBXDLuGxkg0UlkX53ETCUZQo7e/PyhtYWqrwa9uoGJuLMJYZUDJ2D2dH5v8qXXDyllvvq/riX73rqIMQ7zh8QLgpfEJazfp9gu7vztv96oJnQlU3DOqiVYjguBV6Yx7ocVTQXFOuxuLT82Ysb9lgJuh63iJE0PIjGOLxD
  template:
    metadata:
      name: harbor-pull
      namespace: supreal-api
    type: kubernetes.io/dockerconfigjson
